#!/bin/bash
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=altimeter --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=appTemp --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=appTemp1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=barometer --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=cloudbase --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co2_Batt --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co2_Hum --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co2_Temp --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=consBatteryVoltage --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=dewpoint --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=dewpoint1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=dewpoint2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=ET --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=ET_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraHumid1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraHumid2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraHumid3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraHumid4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraHumid5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraHumid6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraHumid7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraHumid8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraTemp1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraTemp2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraTemp3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraTemp4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraTemp5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraTemp6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraTemp7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=extraTemp8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=forecast --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=heatindex --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=heatindex1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=heatindex2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=humidex --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=humidex1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=inDewpoint --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=inHumidity --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=inTemp --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=inTempBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafTemp1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafTemp2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWet1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWet2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=luminosity --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=maxSolarRad --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=outHumidity --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=outHumidity_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=outTemp --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=outTempBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=outTemp_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=outWetbulb --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=outWetbulb_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm10_0 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm1_0 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm2_5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pressure --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=radiation --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=radiation_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rain --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rainBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rainBatteryStatus_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rainDur --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rainDur_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rainRate --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rainRate_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rain_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssir --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssiw --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rssi_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercenta --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercentr --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercentw --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=rxCheckPercent_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signala --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signalr --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signalw --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoist1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoist2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoist3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoist4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTemp1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTemp2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTemp3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTemp4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=solarVolt --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=solarVolt_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=sunshineDur --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=sunshineDur_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=sunshine_hours --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=sunshine_time --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=supercapVolt --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=supercapVolt_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=supplyVoltage --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=THSW --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=THSW_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=THW --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=THW_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txBatteryStatus_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txBatteryVolt --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txBatteryVolt_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID2 --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID3 --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID4 --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID5 --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID6 --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID7 --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID8 --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txIDr --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txIDw --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=txID_2 --type=INTEGER
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=UV --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=uvBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=UV_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windchill --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windchill2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windDir --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windDir_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windGust --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windGustDir --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windGustDir_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windGust_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windrun --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windSpeed --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windSpeed_2 --type=REAL

sudo echo "y" | wee_database --config=/etc/weewx7/weewx.conf --add-column=windrun_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx7/weewx.conf --add-column=rssiA --type=REAL

#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=wetbulb_1 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=wetbulb_2 --type=REAL	
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=wetbulb_3 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=wetbulb_4 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=dewpoint_1 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=dewpoint_2 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=dewpoint_3 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=dewpoint_4 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=heatindex_1 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=heatindex_2 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=heatindex_3 --type=REAL
#sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=heatindex_4 --type=REAL
